name: lint

on: [push, pull_request]

jobs:
    format:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup .NET Core
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.0.x
            - name: dotnet format
              run: dotnet format --exclude Lib9c --exclude NineChronicles.RPC.Shared -v=d --no-restore --verify-no-changes
    validate-appsettings-json:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install ajv-cli
              run: yarn global add ajv-cli
            - name: Validate appsettings.*.json
              working-directory: NineChronicles.Headless.Executable
              run: |
                set -evx

                FILES=(appsettings.mainnet.json appsettings.internal.json appsettings.previewnet.json appsettings.json)
                for file in "${FILES[@]}"; do
                  ajv validate -s appsettings-schema.json -d "$file"
                done
    typos:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Check typos
              uses: crate-ci/typos@v1.15.5
